# Examples of how to return binary data from API endpoints
# Should use it to return some binary API response.
# PNG examples are silly but clear enouph.

[[deceit]]
uris = ["/file/base64.png"]
headers = [["Content-Type", "image/png"]]
[[deceit.responses]]
# Defines that `output` property contains base64 string.
output_type = "base64"
output = """
iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAAXNSR0IB2cksfwAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAADNQTFRFAAAAIIH4Nof2RIz3VZT3Ypr3b6L3far3jLT3mb33psb4sc74udT4xNz4y+H41un44fH4BCg2tAAAAAF0Uk5TAEDm2GYAAAAJcEhZcwAALiMAAC4jAXilP3YAAAAHdElNRQfpCwYNOwMCR6P2AAABgElEQVRYw+2XyZKDMAxEIwKxJXn7/68de4AMi3cyVTmgHKhg90NQ3QY/Hnd9e0Goi/J+BuyqV/4kevYgFs3IzjnbjljmT0H+Wzy2IJa5L+U2xVMtYpkntDuUetUgVrlxkdKihJiHBxmVFxHL0IDWZcrIIY6ok4eyOJzbeLtmllvm4zO04bZsArG6htara/S/Q+fEzk5v3M5bR9cEgEHDKCwiWol+hJSyDsUGSeNKmI+4e9iSURkl/dFz2OuQFJKRu67kQog4R5MzKA1rbQSzDR0YJwm3Xa6+inrXSN86EbK/BSfRn7cymIOSzobzc8hVLFvb/BZ8kEr3wQtJG2UWhxWRdmPUhfWGTuagLpFGNC4pe4QWHYvan7fyq1Hs/M5bKrkebrKQXJkV5+SbLEDrm+mU5ywiORT/e+qyIM8jHjXyLKJ+XgWi9LYvjMO1S0BjFqBTHp8MnVmAsk0qvAJ3FuDOQps8M+8/s1BGwIUPfuiUf2DH8oE9UyYLbYiv35v+AD4dKfjLaMdpAAAAAElFTkSuQmCC
"""

[[deceit]]
uris = ["/file/hex.png"]
headers = [["Content-Type", "image/png"]]
[[deceit.responses]]
# Defines that `output` property contains HEX string.
output_type = "hex"
output = """
89504e470d0a1a0a0000000d494844520000002000000020080300000044a48ac6000000017352474201d9c92c7f0000000467414d410000b18f0bfc6105000000206348524d00007a26000080840000fa00000080e8000075300000ea6000003a98000017709cba513c00000033504c54450000000000002828283e3e3e5555556565657171717d7d7d8c8c8c9b9b9bacacacbcbcbccbcbcbd4d4d4e6e7e6edededffffffad1560150000000174524e530040e6d866000000097048597300002e2300002e230178a53f760000000774494d4507e90b060d2a163c43640d0000009f4944415438cbbd92eb0ec32008853dd65bf142dfff6987fd61744d46d7643b8951e4431131e68fc22ac57d253400500828049e01d0fcd0fc83e8cb2c23eea02c0a240685019cecd1f70a5a2622cb0991ed3862016237126f1cf106486415a010ed406d65ca6201f209a4235d80f90acbb9011f72c80595a677ce401579dee0d9ad75e891ce234491cc8077374a79ffb3f4ef7ed6515f76b55101a3b87fa817bb43063b758859fc0000000049454e44ae426082
"""
